version: '3.9'
services:
  ems_client:
    container_name: ems_client
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - ems_server
    ports:
      - 5173:5173
    restart: on-failure
    volumes:
      - ./client/src:/code/src

  ems_server:
    container_name: ems_server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - ems_mongo
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - ./server:/code/src
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb+srv://tazim:tazim@employeemanagementsyste.ebfi9fx.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=tazim

  ems_mongo:
    container_name: ems_mongo
    image: mongo
    ports:
      - 27017:27017